---
- hosts: server
  remote_user: root
  become: true
  tasks:
#    - name: Install Docker
#      yum:
#        name:
#          - docker
#          - docker-compose
#        state: present
#    - name: "Starting and Enabling Docker service"
#      service:
#        name: docker
#        state: started
#        enabled: yes
    - name: Login DockerHub
      shell: docker login -u "{{DOCKER_USERNAME}}" -p "{{DOCKER_PASSWORD}}"
    - name: Copy file
      copy:
        src: docker-compose.yml
        dest: /root/maven/
    - name: Restart docker-compose
      shell: |
          docker compose stop
          docker compose rm -f
          docker compose pull
          docker compose up -d
      args:
          chdir: /root/maven/
...
  
